services:
  todo-db:
    image: diamol/postgres:11.5
    volumes:
        - todo-db:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=todo
    restart:
      unless-stopped

  todo-web:
    image: diamol/ch06-todo-list:latest
    ports:
      - "8080:80"
    environment:
      - Database:Provider=Postgres
    depends_on:
      - todo-db
    secrets:
      - source: postgres-connection
        target: /app/config/secrets.json
    restart:
      unless-stopped

volumes:
    todo-db:
        driver: local

secrets:
    postgres-connection:
        file: ./config/secrets.json
